CREATE DATABASE IF NOT EXISTS Touristguide DEFAULT CHARSET=utf8;
USE Touristguide;

DROP TABLE IF EXISTS ATTRACTION_TAG;
DROP TABLE IF EXISTS TOURISTATTRACTION;
DROP TABLE IF EXISTS TAG;
DROP TABLE IF EXISTS CITY;

CREATE TABLE TAG (
    TAG_ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(30) NOT NULL,
    PRIMARY KEY (TAG_ID)
);

CREATE TABLE CITY (
    CITY_ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(30) NOT NULL,
    PRIMARY KEY (CITY_ID)
);

CREATE TABLE TOURISTATTRACTION (
    ATTRACTION_ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(30) NOT NULL UNIQUE,
    DESCRIPTION VARCHAR(255),
    CITY_ID INT,
    PRIMARY KEY (ATTRACTION_ID),
    FOREIGN KEY (CITY_ID) REFERENCES CITY(CITY_ID) ON DELETE CASCADE
);

CREATE TABLE ATTRACTION_TAG (
    ATTRACTION_ID INT NOT NULL,
    TAG_ID INT NOT NULL,
    PRIMARY KEY (ATTRACTION_ID, TAG_ID),
    FOREIGN KEY (ATTRACTION_ID) REFERENCES TOURISTATTRACTION(ATTRACTION_ID) ON DELETE CASCADE,
    FOREIGN KEY (TAG_ID) REFERENCES TAG(TAG_ID) ON DELETE CASCADE
);